import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.jsx',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['"Public Sans"', ...defaultTheme.fontFamily.sans],
                serif: ['"Noto Serif"', ...defaultTheme.fontFamily.serif],
            },
            colors: {
                'brand-blue': {
                    50:  '#EBF3FA',
                    100: '#D7E7F5',
                    200: '#B0D0EA',
                    300: '#85B7DC',
                    400: '#5796C2',
                    500: '#4382AE',
                    600: '#366E99',
                    700: '#2A5678',
                    800: '#1E3F58',
                    900: '#132838',
                },
                'brand-gold': {
                    50:  '#FDF8EE',
                    100: '#F9EDCF',
                    200: '#F2D99F',
                    300: '#E8C46E',
                    400: '#D4A843',
                    500: '#B8912E',
                    600: '#9A7724',
                },
                'surface-container-high': '#e7e8e9',
                'outline': '#73777e',
                'on-tertiary-container': '#4f3e00',
                'primary': '#123553',
                'error': '#ba1a1a',
                'primary-fixed': '#d0e4ff',
                'inverse-surface': '#2e3132',
                'error-container': '#ffdad6',
                'surface-variant': '#e1e3e4',
                'on-tertiary-fixed-variant': '#574500',
                'on-primary-fixed-variant': '#294968',
                'on-secondary': '#ffffff',
                'on-secondary-fixed-variant': '#35495b',
                'on-error-container': '#93000a',
                'secondary-fixed': '#d0e5fc',
                'on-primary-container': '#9dbce0',
                'surface-dim': '#d9dadb',
                'on-background': '#191c1d',
                'background': '#f8f9fa',
                'tertiary': '#735c00',
                'on-secondary-fixed': '#071d2e',
                'on-surface': '#191c1d',
                'tertiary-fixed': '#ffe088',
                'surface-container-low': '#f3f4f5',
                'secondary': '#4c6074',
                'surface-container': '#edeeef',
                'primary-fixed-dim': '#aac9ee',
                'inverse-on-surface': '#f0f1f2',
                'on-error': '#ffffff',
                'secondary-fixed-dim': '#b4c9df',
                'on-surface-variant': '#43474d',
                'surface-bright': '#f8f9fa',
                'surface': '#f8f9fa',
                'on-secondary-container': '#516578',
                'primary-container': '#2c4c6b',
                'surface-container-highest': '#e1e3e4',
                'tertiary-container': '#cca830',
                'outline-variant': '#c3c7ce',
                'on-tertiary-fixed': '#241a00',
                'on-tertiary': '#ffffff',
                'tertiary-fixed-dim': '#e9c349',
                'on-primary': '#ffffff',
                'surface-tint': '#426181',
                'inverse-primary': '#aac9ee',
                'on-primary-fixed': '#001d34',
                'surface-container-lowest': '#ffffff',
                'secondary-container': '#cde2f9'
            },
        },
    },

    plugins: [forms],
};
